### ISSUE TITLE
Server compatibility

### ISSUE THREAD

**Issue by AugedesHorus** [iMoonDay/OnlyNeedOneChest#1]
Hi. I love your mod but, I am having trouble with it on my minecraft server. It seems like it isn't server compatible. Are you planning on fixing it or am I doing something wrong?

**Comment by iMoonDay** [comment]
Can you show me the error log? I haven't updated in a long time, and I don't know what your problem is.

**Comment by AugedesHorus** [comment]
[17:44:05] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2025ms or 40 ticks behind
[17:44:18] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_304
        at com.imoonday.on1chest.client.OnlyNeedOneChestClient.<clinit>(OnlyNeedOneChestClient.java:35) ~[On1Chest-Fabric-1.20.1-0.2.jar:?]
        at com.imoonday.on1chest.network.NetworkHandler.sendToClient(NetworkHandler.java:25) ~[On1Chest-Fabric-1.20.1-0.2.jar:?]
        at com.imoonday.on1chest.utils.StorageSyncManager.update(StorageSyncManager.java:152) ~[On1Chest-Fabric-1.20.1-0.2.jar:?]
        at com.imoonday.on1chest.screen.StorageAssessorScreenHandler.method_7623(StorageAssessorScreenHandler.java:249) ~[On1Chest-Fabric-1.20.1-0.2.jar:?]
        at net.minecraft.class_1703.method_7596(class_1703.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14235(class_3222.java:430) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java:1042) ~[server-intermediary.jar:?]
        at com.imoonday.on1chest.blocks.StorageAccessorBlock.method_9534(StorageAccessorBlock.java:42) ~[On1Chest-Fabric-1.20.1-0.2.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_304
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 27 more

this was in the server console

**Comment by iMoonDay** [comment]
I have fixed this issue and I will update it after testing.

**Comment by aowolfie** [comment]
I was just about to come report this issue. Thanks for the quick fix :D

**Comment by iMoonDay** [comment]
The new version has been updated, please let me know if there are still any problems after updating. If not, I will close the issue.

**Comment by aowolfie** [comment]
Everything seems to be working well and the issue seems to be addressed. I really appreciate the quick update :D 

If you're open to contributors I would be willing to help out in the future.
